import { supabase } from '../api.js'; import { SCHOOL_LAT,SCHOOL_LNG,SCHOOL_RADIUS_METERS } from '../config.js'; import { toast, skel } from '../ui.js';
let scanner=null,lastText=null,lastGeo=null;
export async function render(){ const box=document.getElementById('qrReader'), geoState=document.getElementById('geoState'), res=document.getElementById('scanResult'), btnC=document.getElementById('btnCheckin'), btnG=document.getElementById('btnGpsOnly'); if(!box||!geoState||!res||!btnC||!btnG)return; box.innerHTML='';
  try{ scanner=new Html5Qrcode('qrReader'); await scanner.start({facingMode:'environment'},{fps:10,qrbox:240}, t=>{ lastText=t; res.textContent='QR: '+t; }); }catch(e){ box.innerHTML='<div class="p-4 text-sm text-red-600">ไม่สามารถเปิดกล้อง: '+(e?.message||e)+'</div>'; }
  getGeo(geoState); btnC.onclick=async()=>doCheckin('qr+gps'); btnG.onclick=async()=>doCheckin('gps'); await loadToday(); }
export async function renderHomeRecent(){ const box=document.getElementById('homeCheckins'); if(!box)return; box.innerHTML=skel(5,'52px'); const { data,error }=await supabase.from('checkins').select('id,line_display_name,line_picture_url,created_at,distance_m,within_radius,method,text').order('created_at',{ascending:false}).limit(5);
  if(error){ box.innerHTML='<div class="text-gray-500">โหลดเช็คอินไม่สำเร็จ</div>'; return; } box.innerHTML=(data||[]).map(r=>`<div class="p-2 border border-[#E6EAF0] rounded-lg flex items-center gap-2 bg-white"><img src="${r.line_picture_url||''}" class="w-8 h-8 rounded-full border border-[#E6EAF0]" onerror="this.style.display='none'"><div class="flex-1 min-w-0"><div class="text-sm font-medium truncate">${r.line_display_name||'ไม่ระบุ'}</div><div class="text-[12px] text-gray-500">${new Date(r.created_at).toLocaleString('th-TH',{hour:'2-digit',minute:'2-digit'})} • ${r.method}${r.text?' • '+r.text:''}</div></div><div class="${r.within_radius?'text-green-600':'text-red-600'} text-[12px]">${r.distance_m} m</div></div>`).join('')||'<div class="text-gray-500">ยังไม่มีรายการ</div>'; }
function getGeo(out){ out.textContent='กำลังอ่านตำแหน่ง…'; if(!navigator.geolocation){ out.textContent='อุปกรณ์ไม่รองรับตำแหน่ง'; return; } navigator.geolocation.getCurrentPosition((pos)=>{ const {latitude,longitude,accuracy}=pos.coords; lastGeo={lat:latitude,lng:longitude,accuracy}; const d=dist(SCHOOL_LAT,SCHOOL_LNG,latitude,longitude); const ok=d<=SCHOOL_RADIUS_METERS; out.innerHTML=`ตำแหน่งปัจจุบัน: ${latitude.toFixed(5)}, ${longitude.toFixed(5)} (±${Math.round(accuracy)}m) → ${ok?'<span class="text-green-600">ในเขตเช็คอิน</span>':'<span class="text-red-600">อยู่นอกเขต ('+Math.round(d)+'m)</span>'}`; }, (err)=>{ out.textContent='อ่านตำแหน่งไม่สำเร็จ: '+(err?.message||err); }, {enableHighAccuracy:true,timeout:8000,maximumAge:0}); }
function dist(a,b,c,d){ const R=6371000; const toR=x=>x*Math.PI/180; const dLat=toR(c-a), dLon=toR(d-b); const h=Math.sin(dLat/2)**2+Math.cos(toR(a))*Math.cos(toR(c))*Math.sin(dLon/2)**2; return 2*R*Math.asin(Math.sqrt(h)); }
async function doCheckin(method){ const profile=JSON.parse(localStorage.getItem('LINE_PROFILE')||'null'); if(!profile){ toast('ต้องเข้าสู่ระบบด้วย LINE ก่อน'); return; } if(!lastGeo){ toast('ยังไม่ได้ตำแหน่ง'); return; }
  const distance=dist(SCHOOL_LAT,SCHOOL_LNG,lastGeo.lat,lastGeo.lng); const within=distance<=SCHOOL_RADIUS_METERS;
  const payload={ line_user_id:profile?.userId||null, line_display_name:profile?.displayName||null, line_picture_url:profile?.pictureUrl||null, method, text:lastText||null, lat:lastGeo.lat, lng:lastGeo.lng, accuracy:lastGeo.accuracy, distance_m:Math.round(distance), within_radius:within };
  const { error }=await supabase.from('checkins').insert(payload); if(error){ toast('เช็คอินไม่สำเร็จ'); return; } toast(within?'เช็คอินสำเร็จ ✅':'บันทึกนอกเขต ❗'); await loadToday(); }
async function loadToday(){ const profile=JSON.parse(localStorage.getItem('LINE_PROFILE')||'null'); const box=document.getElementById('todayList'); if(!box)return; box.innerHTML=''; if(!profile){ box.innerHTML='<div class="text-gray-500">ยังไม่เข้าสู่ระบบ</div>'; return; }
  const start=new Date(); start.setHours(0,0,0,0); const { data }=await supabase.from('checkins').select('*').eq('line_user_id',profile.userId).gte('created_at',start.toISOString()).order('created_at',{ascending:false}).limit(20);
  box.innerHTML=(data||[]).map(r=>`<div class="p-2 border border-[#E6EAF0] rounded-lg flex justify-between text-sm"><div>${new Date(r.created_at).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})} — ${r.method}${r.text?' • '+r.text:''}</div><div class="${r.within_radius?'text-green-600':'text-red-600'}">${r.distance_m} m</div></div>`).join('')||'<div class="text-gray-500">ยังไม่มีรายการวันนี้</div>'; }