import { supabase } from '../api.js';
const homeGrid=()=>document.getElementById('homeLinks'); const grid=()=>document.getElementById('linkGrid');
const composeBtn=()=>document.getElementById('btnComposeLink'); const composeBox=()=>document.getElementById('composeLinkBox'); const composeForm=()=>document.getElementById('composeLinkForm');
function skel(n=8){ return Array.from({length:n}).map(()=>`<div class='skeleton h-24'></div>`).join(''); }
export async function renderHome(){ homeGrid().innerHTML=skel(8); const {data}=await supabase.from('app_links').select('id,title,url,image_url,category').eq('is_active',true).order('sort_order').limit(8); homeGrid().innerHTML=(data||[]).map(tile).join('')||'<div class="text-gray-500">ยังไม่มีลิงก์</div>'; }
export async function render(){ grid().innerHTML=skel(10); const editor=await isEditor(); composeBtn().classList.toggle('hide',!editor); composeBox().classList.add('hide'); composeBtn().onclick=()=>composeBox().classList.toggle('hide');
  const {data}=await supabase.from('app_links').select('id,title,url,image_url,category,is_active,sort_order').order('sort_order'); grid().innerHTML=(data||[]).map(r=>tile(r,true,editor)).join('')||'<div class="text-gray-500">ยังไม่มีลิงก์</div>';
  const input=document.getElementById('linkImage'); if(input){ input.onchange=async()=>{ const f=input.files?.[0]; if(!f) return; const path=`app-icons/${Date.now()}_${f.name}`; const up=await supabase.storage.from('app-icons').upload(path,f,{upsert:false,contentType:f.type}); if(up.error){ alert('อัปโหลดรูปไม่สำเร็จ: '+up.error.message); return; } const url=supabase.storage.from('app-icons').getPublicUrl(path).data.publicUrl; composeForm().elements['image_url'].value=url; }; }
  composeForm().onsubmit=async(e)=>{ e.preventDefault(); const fd=new FormData(composeForm()); const payload={ title:fd.get('title'), url:fd.get('url'), image_url:fd.get('image_url')||null, category:fd.get('category')||null, sort_order:Number(fd.get('sort_order')||100), is_active:!!fd.get('is_active') };
    const {error}=await supabase.from('app_links').insert(payload); if(error){ alert('บันทึกไม่สำเร็จ: '+error.message); return; } composeForm().reset(); composeBox().classList.add('hide'); await render(); }; }
function tile(r,full=false,editor=false){ const img=r.image_url?`<img src='${r.image_url}' class='w-12 h-12 object-cover rounded-2xl border border-[#E6EAF0]' alt='icon'>`:`<div class='w-12 h-12 rounded-2xl grid place-items-center bg-brandSoft text-brand'>🔗</div>`; const actions=editor&&full?`<div class='flex gap-2 justify-center mt-1'><button class='btn text-xs' onclick='editLink(${r.id})'>แก้ไข</button><button class='btn text-xs' onclick='deleteLink(${r.id})'>ลบ</button></div>`:''; return `<div class='flex flex-col items-center gap-1'><a href='${encodeURI(r.url)}' target='_blank' rel='noopener'>${img}<div class='text-[12px] text-center leading-tight mt-1'>${e(r.title)}</div></a>${actions}</div>`; }
window.editLink=async function(id){ const {data:r}=await supabase.from('app_links').select('*').eq('id',id).maybeSingle(); if(!r) return alert('ไม่พบรายการ'); const title=prompt('ชื่อแอป',r.title); if(title===null) return; const url=prompt('URL',r.url); if(url===null) return; const image_url=prompt('รูป (image_url)',r.image_url||''); if(image_url===null) return; const sort_order=Number(prompt('ลำดับแสดง', r.sort_order??100)||100); const is_active=confirm('แสดงผลรายการนี้หรือไม่? (OK=แสดง, Cancel=ซ่อน)'); const {error}=await supabase.from('app_links').update({title,url,image_url,sort_order,is_active}).eq('id',id); if(error) return alert('บันทึกไม่สำเร็จ: '+error.message); await window.__refreshLinks(); };
window.deleteLink=async function(id){ if(!confirm('ลบรายการนี้?')) return; const {error}=await supabase.from('app_links').delete().eq('id',id); if(error) return alert('ลบไม่สำเร็จ: '+error.message); await window.__refreshLinks(); };
window.__refreshLinks=async function(){ await import('./links.js').then(m=>m.render()); };
async function isEditor(){ const {data:session}=await supabase.auth.getUser(); const u=session.user; if(!u) return false; const {data}=await supabase.from('editors').select('user_id').eq('user_id',u.id).maybeSingle(); return !!data; }
function e(s){ return (s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); }