import { supabase } from '../api.js';
const homeBox=()=>document.getElementById('homeNews'); const listBox=()=>document.getElementById('newsList');
const composeBtn=()=>document.getElementById('btnComposePost'); const composeBox=()=>document.getElementById('composePostBox'); const composeForm=()=>document.getElementById('composePostForm');
const postDetail=()=>document.getElementById('postDetail'); const postEditor=()=>document.getElementById('postEditor'); const editForm=()=>document.getElementById('editPostForm');
function skel(n=3,h='64px'){ return Array.from({length:n}).map(()=>`<div class='skeleton' style='height:${h}'></div>`).join(''); }
export async function renderHome(){ homeBox().innerHTML=skel(3,'56px'); const {data}=await supabase.from('posts').select('id,title,category,published_at,cover_url').lte('published_at',new Date().toISOString()).order('published_at',{ascending:false}).limit(6); homeBox().innerHTML=(data||[]).map(card).join('')||empty('ยังไม่มีข่าว'); }
export async function renderList(){ listBox().innerHTML=skel(6,'72px'); const editor=await isEditor(); composeBtn().classList.toggle('hide',!editor); composeBox().classList.add('hide'); composeBtn().onclick=()=>composeBox().classList.toggle('hide');
  const cover=document.getElementById('postCover'); if(cover){ cover.onchange=async()=>{ const f=cover.files?.[0]; if(!f) return; const path=`news-covers/${Date.now()}_${f.name}`; const up=await supabase.storage.from('news-covers').upload(path,f,{upsert:false,contentType:f.type}); if(up.error){ alert('อัปโหลดปกไม่สำเร็จ: '+up.error.message); return; } const url=supabase.storage.from('news-covers').getPublicUrl(path).data.publicUrl; composeForm().elements['cover_url'].value=url; }; }
  const {data}=await supabase.from('posts').select('id,title,category,published_at,cover_url').order('published_at',{ascending:false}).limit(50); listBox().innerHTML=(data||[]).map(card).join('')||empty('ยังไม่มีข่าว');
  composeForm().onsubmit=async(e)=>{ e.preventDefault(); const fd=new FormData(composeForm()); const payload={ title:fd.get('title'), category:fd.get('category')||null, body:fd.get('body')||null, cover_url:fd.get('cover_url')||null, published_at:fd.get('published_at')?new Date(fd.get('published_at')).toISOString():new Date().toISOString() }; const {data:row,error}=await supabase.from('posts').insert(payload).select('id').single(); if(error){ alert('บันทึกข่าวไม่สำเร็จ: '+error.message); return; } composeForm().reset(); composeBox().classList.add('hide'); location.hash=`#post?id=${row.id}`; }; }
export async function renderDetail(id){ postDetail().innerHTML=skel(4,'80px'); const {data:p,error}=await supabase.from('posts').select('id,title,category,body,cover_url,published_at,created_by').eq('id',id).maybeSingle(); if(error||!p){ postDetail().innerHTML=empty('ไม่พบข่าว'); return; }
  const cover=p.cover_url?`<img class='cover mb-3' src='${p.cover_url}' alt='cover'>`:''; const md=window.marked?window.marked.parse(p.body||''):(p.body||''); const safe=window.DOMPurify?window.DOMPurify.sanitize(md):md; const d=p.published_at?new Date(p.published_at).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'}):''; postDetail().innerHTML=`${cover}<h1 class='text-xl font-semibold mb-1'>${e(p.title)}</h1><div class='text-xs text-gray-500 mb-3'>${e(p.category||'ทั่วไป')} • ${d}</div><div class='prose prose-sm max-w-none'>${safe}</div>`;
  const editor=await isEditor(p.created_by); postEditor().classList.toggle('hide',!editor); if(editor){ editForm().elements['title'].value=p.title||''; editForm().elements['category'].value=p.category||''; editForm().elements['body'].value=p.body||''; editForm().elements['cover_url'].value=p.cover_url||''; editForm().elements['published_at'].value=p.published_at?new Date(p.published_at).toISOString().slice(0,16):''; document.getElementById('editPostCover').onchange=async(ev)=>{ const f=ev.target.files?.[0]; if(!f) return; const path=`news-covers/${Date.now()}_${f.name}`; const up=await supabase.storage.from('news-covers').upload(path,f,{upsert:false,contentType:f.type}); if(up.error){ alert('อัปโหลดปกไม่สำเร็จ: '+up.error.message); return; } const url=supabase.storage.from('news-covers').getPublicUrl(path).data.publicUrl; editForm().elements['cover_url'].value=url; };
    editForm().onsubmit=async(e)=>{ e.preventDefault(); const fd=new FormData(editForm()); const upd={ title:fd.get('title'), category:fd.get('category')||null, body:fd.get('body')||null, cover_url:fd.get('cover_url')||null, published_at:fd.get('published_at')?new Date(fd.get('published_at')).toISOString():null, updated_at:new Date().toISOString() }; const {error}=await supabase.from('posts').update(upd).eq('id',p.id); if(error){ alert('บันทึกไม่สำเร็จ: '+error.message); return; } await renderDetail(p.id); };
    document.getElementById('btnDeletePost').onclick=async()=>{ if(!confirm('ลบข่าวนี้?')) return; const {error}=await supabase.from('posts').delete().eq('id',p.id); if(error){ alert('ลบไม่สำเร็จ: '+error.message); return; } location.hash='#news'; }; } }
function card(p){ const open=`location.hash='#post?id=${p.id}'`; const d=new Date(p.published_at||new Date()).toLocaleDateString('th-TH'); const img=p.cover_url?`<img class='w-16 h-16 object-cover rounded-lg border border-[#E6EAF0]' src='${p.cover_url}' alt='cover'>`:`<div class='w-16 h-16 rounded-lg bg-brandSoft grid place-items-center text-brand'>📰</div>`; return `<article class='p-3 border border-[#E6EAF0] rounded-xl bg-white flex items-center gap-3 cursor-pointer' onclick='${open}'>${img}<div class='flex-1'><div class='font-semibold line-clamp-2'>${e(p.title)}</div><div class='text-[12px] text-gray-500'>${e(p.category||'ทั่วไป')} • ${d}</div></div><div class='text-brand text-sm'>อ่านต่อ ›</div></article>`; }
async function isEditor(created_by){ const {data:session}=await supabase.auth.getUser(); const u=session.user; if(!u) return false; if(created_by&&created_by===u.id) return true; const {data}=await supabase.from('editors').select('user_id').eq('user_id',u.id).maybeSingle(); return !!data; }
function empty(t){ return `<div class='text-gray-500'>${e(t)}</div>`; }
function e(s){ return (s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); }