import { supabase } from '../api.js';
import { openSheet, closeSheet, toast, skel, esc } from '../ui.js';
const PAGE_SIZE=10; let page=1,total=0,sliderTimer=null;
export async function renderHome(){ const listEl=document.getElementById('homeNewsList'); const cardsEl=document.getElementById('homeNewsCards'); if(!listEl||!cardsEl)return;
  listEl.innerHTML=skel(2); cardsEl.innerHTML=skel(3,'180px');
  const latestResp=await supabase.from('posts').select('id,title,category,published_at,cover_url,is_featured').lte('published_at',new Date().toISOString()).order('published_at',{ascending:false}).limit(8);
  const latest=latestResp.data||[]; const featuredResp=await supabase.from('posts').select('id,title,category,published_at,cover_url,is_featured').eq('is_featured',true).order('published_at',{ascending:false}).limit(12);
  const featured=featuredResp.data||[]; const top2=latest.slice(0,2); const top2Ids=new Set(top2.map(x=>x.id)); const pool=[...featured,...latest.filter(p=>!top2Ids.has(p.id))];
  const picked=[]; const seen=new Set(); for(const p of pool){ if(picked.length>=3) break; if(top2Ids.has(p.id)||seen.has(p.id)) continue; picked.push(p); seen.add(p.id); }
  listEl.innerHTML=top2.map(p=>`<div class='p-3 border rounded-xl bg-[var(--card)] flex items-center gap-3' style='border-color:var(--bd)'><a class='flex-shrink-0' href='#post?id=${p.id}'>${p.cover_url?`<img class='w-16 h-16 object-cover rounded-lg border' src='${p.cover_url}'>`:`<div class='w-16 h-16 rounded-lg bg-brandSoft grid place-items-center text-brand'>📰</div>`}</a><div class='flex-1'><a href='#post?id=${p.id}' class='font-semibold leading-snug line-clamp-2' style='color:var(--ink)'>${esc(p.title)}</a><div class='text-[12px] text-ink3'>${esc(p.category||'ทั่วไป')} • ${new Date(p.published_at).toLocaleDateString('th-TH')}</div></div></div>`).join('')||'<div class="text-ink3">ยังไม่มีข่าว</div>';
  const ids=picked.map(p=>p.id); const statMap=await fetchStats(ids);
  cardsEl.innerHTML=picked.map(p=>{ const s=statMap.get(p.id)||{views:0,likes:0}; return `<div class='news-card'><a href='#post?id=${p.id}'>${p.cover_url?`<img class='thumb' src='${p.cover_url}'>`:`<div class='thumb grid place-items-center bg-brandSoft text-brand'>📰</div>`}</a><div class='badge'>เด่น</div><div class='p-3'><div class='text-[12px] text-ink3 mb-1'>${esc(p.category||'ทั่วไป')} • ${new Date(p.published_at).toLocaleDateString('th-TH')}</div><a class='font-semibold leading-snug line-clamp-2 block' href='#post?id=${p.id}' style='color:var(--ink)'>${esc(p.title)}</a><div class='flex items-center gap-3 mt-2 text-[12px] text-ink2'><span>👁️ ${s.views}</span><span>❤️ ${s.likes}</span><button onclick='sharePost(${p.id})' class='underline'>แชร์</button></div></div></div>`; }).join('');
  const isSmall=matchMedia && matchMedia('(max-width: 640px)').matches; if(isSmall){ cardsEl.classList.add('slider'); const ms=4000; clearInterval(sliderTimer); sliderTimer=setInterval(()=>{ try{ const w=cardsEl.clientWidth; const next=Math.round((cardsEl.scrollLeft+w)/w); const max=cardsEl.children.length-1; const to=(next>max?0:next)*w; cardsEl.scrollTo({left:to,behavior:'smooth'});}catch(_){}} ,ms); } else { if(sliderTimer) clearInterval(sliderTimer); }
}
export async function renderList(){ const box=document.getElementById('newsList'); if(!box)return; const btn=document.getElementById('btnComposePost'); const can=await canManageContent(); if(btn){ btn.classList.toggle('hide',!can); btn.onclick=()=>openComposeSheet(); }
  await loadPage(1); const prev=document.getElementById('btnPrev'), next=document.getElementById('btnNext'); if(prev) prev.onclick=()=>{ if(page>1) loadPage(page-1); }; if(next) next.onclick=()=>{ const max=Math.ceil(total/PAGE_SIZE)||1; if(page<max) loadPage(page+1); }; }
async function loadPage(p){ page=p; const box=document.getElementById('newsList'); if(!box)return; box.innerHTML=skel(PAGE_SIZE,'72px');
  const from=(page-1)*PAGE_SIZE, to=from+PAGE_SIZE-1; const resp=await supabase.from('posts').select('id,title,category,published_at,cover_url,created_by',{count:'exact'}).order('published_at',{ascending:false}).range(from,to);
  const data=resp.data||[]; total=resp.count||0; const ids=data.map(x=>x.id); const statMap=await fetchStats(ids); const can=await canManageContent();
  box.innerHTML=data.map(p=>{ const s=statMap.get(p.id)||{views:0,likes:0}; const tools=can?`<div class='flex gap-2 mt-1'><button class='btn text-xs' onclick='editPost(${p.id})'>แก้ไข</button><button class='btn text-xs' onclick='deletePost(${p.id})'>ลบ</button></div>`:''; return `<article class='p-3 border rounded-xl bg-[var(--card)] flex items-center gap-3' style='border-color:var(--bd)'><a class='flex-shrink-0' href='#post?id=${p.id}'>${p.cover_url?`<img class='w-16 h-16 object-cover rounded-lg border' src='${p.cover_url}'>`:`<div class='w-16 h-16 rounded-lg bg-brandSoft grid place-items-center text-brand'>📰</div>`}</a><div class='flex-1'><a href='#post?id=${p.id}' class='font-semibold leading-snug line-clamp-2' style='color:var(--ink)'>${esc(p.title)}</a><div class='text-[12px] text-ink3'>${esc(p.category||'ทั่วไป')} • ${new Date(p.published_at).toLocaleDateString('th-TH')}</div><div class='flex items-center gap-3 mt-1 text-[12px] text-ink2'><span>👁️ ${s.views}</span><span>❤️ ${s.likes}</span><button onclick='sharePost(${p.id})' class='underline'>แชร์</button></div>${tools}</div></article>`; }).join('')||'<div class="text-ink3">ยังไม่มีข่าว</div>';
  const info=document.getElementById('pageInfo'); if(info){ const max=Math.ceil(total/PAGE_SIZE)||1; info.textContent=`หน้า ${page} / ${max} • ทั้งหมด ${total} ข่าว`; }
}
export async function renderDetail(id){ const box=document.getElementById('postDetail'); if(!box)return; box.innerHTML=skel(4,'80px'); const resp=await supabase.from('posts').select('id,title,category,body,cover_url,published_at,created_by,is_featured').eq('id',id).maybeSingle(); const p=resp.data; if(!p){ box.innerHTML='<div class="text-ink3">ไม่พบข่าว</div>'; return; }
  try{ await supabase.rpc('increment_view',{p_post_id:p.id}); }catch{}
  const statResp=await supabase.from('post_stats').select('view_count,like_count').eq('post_id',p.id).maybeSingle(); const views=(statResp.data&&statResp.data.view_count)||0; const likes=(statResp.data&&statResp.data.like_count)||0;
  const prof=JSON.parse(localStorage.getItem('LINE_PROFILE')||'null'); const lineId=prof?.userId||null; let liked=false; if(lineId){ const lk=await supabase.from('post_likes').select('post_id').eq('post_id',p.id).eq('line_user_id',lineId).maybeSingle(); liked=!!lk.data; }
  const cover=p.cover_url?`<img class='cover mb-3' src='${p.cover_url}'>`:''; const md=window.marked?window.marked.parse(p.body||''):(p.body||''); const safe=window.DOMPurify?window.DOMPurify.sanitize(md):md; const d=p.published_at?new Date(p.published_at).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'}):''; const can=await canManageContent(p.created_by);
  box.innerHTML=`${cover}<h1 class='text-xl font-semibold mb-1'>${esc(p.title)}</h1><div class='text-xs text-ink3 mb-3'>${esc(p.category||'ทั่วไป')} • ${d}</div><div class='prose prose-sm max-w-none mb-4' style='color:var(--ink)'>${safe}</div><div class='flex items-center gap-2'><button id='btnLike' class='btn' aria-pressed='${liked}'>${liked?'❤️':'🤍'} <span id='likeCount' class='ml-1'>${likes}</span></button><button id='btnShare' class='btn'>แชร์ LINE</button><div class='ml-auto text-sm text-ink3'>เปิดอ่าน <span id='viewCount'>${views}</span> ครั้ง</div></div>${can?`<div class='mt-3 flex gap-2'><button class='btn btn-prim' id='editP'>แก้ไข</button><button class='btn' id='delP'>ลบ</button></div>`:''}`;
  const editBtn=document.getElementById('editP'), delBtn=document.getElementById('delP'); if(editBtn) editBtn.onclick=()=>openEditSheet(p); if(delBtn) delBtn.onclick=async()=>{ if(!confirm('ลบข่าวนี้?'))return; const del=await supabase.from('posts').delete().eq('id',p.id); if(del.error){toast('ลบไม่สำเร็จ');return;} location.hash='#news'; };
  const likeBtn=document.getElementById('btnLike'); if(likeBtn){ likeBtn.onclick=async()=>{ if(!lineId){toast('กรุณาเข้าสู่ระบบด้วย LINE ก่อน');return;} const pressed=(likeBtn.getAttribute('aria-pressed')==='true'); try{ if(pressed){ const res=await supabase.rpc('unlike_post',{p_post_id:p.id,p_line_user_id:lineId}); likeBtn.setAttribute('aria-pressed','false'); likeBtn.firstChild.nodeValue='🤍'; document.getElementById('likeCount').textContent=(res.data||0);} else { const res=await supabase.rpc('like_post',{p_post_id:p.id,p_line_user_id:lineId}); likeBtn.setAttribute('aria-pressed','true'); likeBtn.firstChild.nodeValue='❤️'; document.getElementById('likeCount').textContent=(res.data||0);} }catch{ toast('ดำเนินการไม่สำเร็จ'); } }; }
  setTimeout(async()=>{ const s2=await supabase.from('post_stats').select('view_count').eq('post_id',p.id).maybeSingle(); if(s2.data&&document.getElementById('viewCount')) document.getElementById('viewCount').textContent=s2.data.view_count; },1200);
  const btnShare=document.getElementById('btnShare'); if(btnShare){ btnShare.onclick=()=>sharePost(p.id); }
}
async function fetchStats(ids){ const map=new Map(); if(!ids||ids.length===0) return map; const resp=await supabase.from('post_stats').select('post_id,view_count,like_count').in('post_id',ids); (resp.data||[]).forEach(r=>map.set(r.post_id,{views:r.view_count||0,likes:r.like_count||0})); return map; }
window.sharePost=async function(id){ const base=(localStorage.getItem('APPWD_PUBLIC_URL')||'./'); const row=await supabase.from('posts').select('id,title,category,cover_url').eq('id',id).maybeSingle(); const p=row.data; if(!p){ toast('ไม่พบบทความ'); return; } const url=base+`index.html#post?id=${p.id}`; const bubble={type:'bubble',hero:p.cover_url?{type:'image',url:p.cover_url,size:'full',aspectRatio:'16:9',aspectMode:'cover'}:undefined,body:{type:'box',layout:'vertical',contents:[{type:'text',text:p.title||'ข่าว',weight:'bold',size:'md',wrap:true},{type:'text',text:(p.category||'ทั่วไป'),size:'xs',color:'#6B7280',wrap:true,margin:'sm'}]},footer:{type:'box',layout:'vertical',spacing:'sm',contents:[{type:'button',style:'primary',height:'sm',action:{type:'uri',label:'อ่านข่าว',uri:url}}]}}; try{ if(window.liff&&window.liff.isApiAvailable&&window.liff.isApiAvailable('shareTargetPicker')){ await window.liff.shareTargetPicker([{type:'flex',altText:`แชร์ข่าว: ${p.title}`,contents:bubble}]); } else { await navigator.clipboard.writeText(url); toast('คัดลอกลิงก์แล้ว'); } }catch(e){ toast('แชร์ไม่สำเร็จ'); } };
async function canManageContent(created_by){ const auth=await supabase.auth.getUser(); const user=auth.data&&auth.data.user; if(user && created_by && user.id===created_by) return true; if(user){ const ed=await supabase.from('editors').select('user_id').eq('user_id',user.id).maybeSingle(); if(ed.data) return true; } const prof=JSON.parse(localStorage.getItem('LINE_PROFILE')||'null'); const lineId=prof?.userId||null; if(lineId){ const u=await supabase.from('users').select('role').eq('line_user_id',lineId).maybeSingle(); if(u.data && (u.data.role==='admin'||u.data.role==='editor')) return true; } return false; }
function openComposeSheet(){ openSheet(`<form id='composePostForm' class='grid gap-2 text-sm'><input name='title' placeholder='หัวข้อข่าว' class='border rounded p-2' required><input name='category' placeholder='หมวด' class='border rounded p-2'><input name='cover_url' placeholder='ลิงก์ภาพปก (cover_url)' class='border rounded p-2'><label class='text-sm flex items-center gap-2'><input type='checkbox' name='is_featured'> ปักหมุด/สติกเกอร์</label><textarea name='body' rows='8' placeholder='เนื้อหา (Markdown)' class='border rounded p-2'></textarea><label class='text-sm'>เผยแพร่: <input type='datetime-local' name='published_at' class='border rounded p-1'></label><div class='flex gap-2'><button class='btn btn-prim'>บันทึก</button><button type='button' id='cancelSheet' class='btn'>ยกเลิก</button></div></form>`); const cancel=document.getElementById('cancelSheet'); if(cancel) cancel.onclick=closeSheet; const form=document.getElementById('composePostForm'); if(form){ form.onsubmit=async e=>{ e.preventDefault(); const fd=new FormData(form); const payload={ title:fd.get('title'), category:fd.get('category')||null, body:fd.get('body')||null, cover_url:fd.get('cover_url')||null, is_featured:!!fd.get('is_featured'), published_at:fd.get('published_at')?new Date(fd.get('published_at')).toISOString():new Date().toISOString() }; const ins=await supabase.from('posts').insert(payload).select('id').single(); if(ins.error){ toast('บันทึกข่าวไม่สำเร็จ'); return; } closeSheet(); location.hash=`#post?id=${ins.data.id}`; }; } }
function openEditSheet(p){ openSheet(`<form id='editPostForm' class='grid gap-2 text-sm'><input name='title' class='border rounded p-2' value='${esc(p.title||'')}'><input name='category' class='border rounded p-2' value='${esc(p.category||'')}'><input name='cover_url' class='border rounded p-2' value='${esc(p.cover_url||'')}' placeholder='ลิงก์ภาพปก'><label class='text-sm flex items-center gap-2'><input type='checkbox' name='is_featured' ${p.is_featured?'checked':''}> ปักหมุด/สติกเกอร์</label><textarea name='body' rows='10' class='border rounded p-2'>${esc(p.body||'')}</textarea><label class='text-sm'>เผยแพร่: <input type='datetime-local' name='published_at' class='border rounded p-1' value='${p.published_at? new Date(p.published_at).toISOString().slice(0,16):''}'></label><div class='flex gap-2'><button class='btn btn-prim'>บันทึก</button><button type='button' id='cancelSheet' class='btn'>ยกเลิก</button></div></form>`); const cancel=document.getElementById('cancelSheet'); if(cancel) cancel.onclick=closeSheet; const form=document.getElementById('editPostForm'); if(form){ form.onsubmit=async e=>{ e.preventDefault(); const fd=new FormData(form); const upd={ title:fd.get('title'), category:fd.get('category')||null, body:fd.get('body')||null, cover_url:fd.get('cover_url')||null, is_featured:!!fd.get('is_featured'), published_at:fd.get('published_at')?new Date(fd.get('published_at')).toISOString():null, updated_at:new Date().toISOString() }; const up=await supabase.from('posts').update(upd).eq('id',p.id); if(up.error){ toast('บันทึกไม่สำเร็จ'); return; } toast('บันทึกแล้ว'); closeSheet(); location.hash=`#post?id=${p.id}`; }; } }
window.editPost=async function(id){ const { data }=await supabase.from('posts').select('*').eq('id',id).maybeSingle(); if(!data) return; openEditSheet(data); }
window.deletePost=async function(id){ if(!confirm('ลบข่าวนี้?')) return; const del=await supabase.from('posts').delete().eq('id',id); if(del.error){toast('ลบไม่สำเร็จ');return;} toast('ลบแล้ว'); await import('./news.js').then(m=>m.renderList()); }

// Bottom Sheet editor for post (create/update)
export async function openPostEditor(id){
  let row = { title:'', category:'ประกาศ', cover_url:'', body:'' };
  if(id){
    const res = await supabase.from('posts').select('*').eq('id', id).maybeSingle();
    if(!res.error && res.data) row = res.data;
  }
  const form = `
    <form id="editPostForm" class="form-grid">
      <label>หัวข้อ<input name="title" value="${esc(row.title||'')}" /></label>
      <label>หมวดหมู่<input name="category" value="${esc(row.category||'ประกาศ')}" /></label>
      <label>ภาพปก (URL)<input name="cover_url" value="${esc(row.cover_url||'')}" /></label>
      <label>เนื้อหา (Markdown)<textarea rows="10" name="body">${esc(row.body||'')}</textarea></label>
    </form>`;
  openSheet(form, { title: id?'แก้ไขข่าว':'เพิ่มข่าว', actions:`
    <div class="flex gap-2 justify-between">
      <button class="btn" id="postCancel">ยกเลิก</button>
      <button class="btn btn-prim" id="postSave">บันทึก</button>
    </div>`
  });
  document.getElementById('postCancel')?.addEventListener('click', closeSheet);
  document.getElementById('postSave')?.addEventListener('click', async ()=>{
    const fd = new FormData(document.getElementById('editPostForm'));
    const payload = {
      title: (fd.get('title')||'').trim(),
      category: (fd.get('category')||'').trim(),
      cover_url: String(fd.get('cover_url')||'').trim() || null,
      body: fd.get('body')||'',
      updated_at: new Date().toISOString()
    };
    let ret;
    if(id) ret = await supabase.from('posts').update(payload).eq('id', id);
    else ret = await supabase.from('posts').insert([payload]).select().maybeSingle();
    if(ret.error){ toast('บันทึกไม่สำเร็จ','error'); return; }
    toast('บันทึกแล้ว','ok'); closeSheet();
    document.dispatchEvent(new CustomEvent('appwd:postSaved', { detail: { id: id || ret?.data?.id } }));
  });
}
window.editPost = openPostEditor;
