import { supabase } from '../api.js';
import { toast, markLoaded } from '../ui.js';
const homeBox=()=>document.getElementById('homeNews'); const listBox=()=>document.getElementById('newsList');
function skel(n=3,h='56px'){ return Array.from({length:n}).map(()=>`<div class="skeleton" style="height:${h}"></div>`).join(''); }
export async function renderHero(){ const slides=document.getElementById('heroSlides'); slides.innerHTML=`<div class="swiper-slide"><div class="skeleton h-40"></div></div>`.repeat(3); const {data}=await supabase.from('posts').select('id,title,cover_url,published_at').order('published_at',{ascending:false}).limit(6); const items=(data||[]).slice(0,5); slides.innerHTML=items.map(p=>slide(p)).join('')||`<div class="swiper-slide"><div class="p-6">ยังไม่มีข่าว</div></div>`; const swiper=new Swiper('#heroSwiper',{ loop:items.length>1, autoplay:{delay:4500,disableOnInteraction:false}, pagination:{el:'.swiper-pagination',clickable:true} }); }
function slide(p){ const img=p.cover_url?`<img src="${p.cover_url}" class="w-full h-48 object-cover" onload="import('./ui.js').then(m=>m.markLoaded(this))">`:`<div class="w-full h-48 grid place-items-center bg-[#EAF2FF]">📰</div>`; return `<div class="swiper-slide"><a href="javascript:location.hash='#post?id=${p.id}'" class="block">${img}<div class="p-3 text-sm font-semibold line-clamp-2">${e(p.title)}</div></a></div>`; }
export async function renderHome(){ homeBox().innerHTML=skel(3); const {data}=await supabase.from('posts').select('id,title,category,published_at,cover_url').lte('published_at',new Date().toISOString()).order('published_at',{ascending:false}).limit(6); homeBox().innerHTML=(data||[]).map(card).join('')||empty('ยังไม่มีข่าว'); }
export async function renderList(){ listBox().innerHTML=skel(8,'72px'); const editor=await isEditor(); const btn=document.getElementById('btnComposePost'); const box=document.getElementById('composePostBox'); const form=document.getElementById('composePostForm'); btn.classList.toggle('hide',!editor); box.classList.add('hide'); btn.onclick=()=>box.classList.toggle('hide');
  const cover=document.getElementById('postCover'); if(cover){ cover.onchange=async()=>{ const f=cover.files?.[0]; if(!f) return; const path=`news-covers/${Date.now()}_${f.name}`; const up=await supabase.storage.from('news-covers').upload(path,f,{upsert:false,contentType:f.type}); if(up.error){ toast('อัปโหลดปกไม่สำเร็จ'); return; } const url=supabase.storage.from('news-covers').getPublicUrl(path).data.publicUrl; form.elements['cover_url'].value=url; toast('อัปโหลดปกแล้ว'); }; }
  const {data}=await supabase.from('posts').select('id,title,category,published_at,cover_url').order('published_at',{ascending:false}).limit(50); listBox().innerHTML=(data||[]).map(card).join('')||empty('ยังไม่มีข่าว');
  form.onsubmit=async(e)=>{ e.preventDefault(); const fd=new FormData(form); const payload={ title:fd.get('title'), category:fd.get('category')||null, body:fd.get('body')||null, cover_url:fd.get('cover_url')||null, published_at:fd.get('published_at')?new Date(fd.get('published_at')).toISOString():new Date().toISOString() }; const {data:row,error}=await supabase.from('posts').insert(payload).select('id').single(); if(error){ toast('บันทึกข่าวไม่สำเร็จ'); return; } form.reset(); box.classList.add('hide'); location.hash=`#post?id=${row.id}`; }; }
export async function renderDetail(id){ const box=document.getElementById('postDetail'); box.innerHTML=skel(4,'80px'); const {data:p,error}=await supabase.from('posts').select('id,title,category,body,cover_url,published_at,created_by').eq('id',id).maybeSingle(); if(error||!p){ box.innerHTML=empty('ไม่พบข่าว'); return; } const cover=p.cover_url?`<img class="cover mb-3" src="${p.cover_url}" onload="import('../ui.js').then(m=>m.markLoaded(this))" alt="cover">`:''; const md=window.marked?window.marked.parse(p.body||''):(p.body||''); const safe=window.DOMPurify?window.DOMPurify.sanitize(md):md; const d=p.published_at?new Date(p.published_at).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'}):''; box.innerHTML=`${cover}<h1 class="text-xl font-semibold mb-1">${e(p.title)}</h1><div class="text-xs text-gray-500 mb-3">${e(p.category||'ทั่วไป')} • ${d}</div><div class="prose prose-sm max-w-none">${safe}</div>`;
  const editor=await isEditor(p.created_by); const tools=document.getElementById('postEditor'); const form=document.getElementById('editPostForm'); tools.classList.toggle('hide',!editor); if(editor){ form.elements['title'].value=p.title||''; form.elements['category'].value=p.category||''; form.elements['body'].value=p.body||''; form.elements['cover_url'].value=p.cover_url||''; form.elements['published_at'].value=p.published_at?new Date(p.published_at).toISOString().slice(0,16):''; document.getElementById('editPostCover').onchange=async(ev)=>{ const f=ev.target.files?.[0]; if(!f) return; const path=`news-covers/${Date.now()}_${f.name}`; const up=await supabase.storage.from('news-covers').upload(path,f,{upsert:false,contentType:f.type}); if(up.error){ toast('อัปโหลดปกไม่สำเร็จ'); return; } const url=supabase.storage.from('news-covers').getPublicUrl(path).data.publicUrl; form.elements['cover_url'].value=url; toast('อัปปกแล้ว'); }; form.onsubmit=async(e)=>{ e.preventDefault(); const fd=new FormData(form); const upd={ title:fd.get('title'), category:fd.get('category')||null, body:fd.get('body')||null, cover_url:fd.get('cover_url')||null, published_at:fd.get('published_at')?new Date(fd.get('published_at')).toISOString():null, updated_at:new Date().toISOString() }; const {error}=await supabase.from('posts').update(upd).eq('id',p.id); if(error){ toast('บันทึกไม่สำเร็จ'); return; } toast('บันทึกแล้ว'); await renderDetail(p.id); }; document.getElementById('btnDeletePost').onclick=async()=>{ if(!confirm('ลบข่าวนี้?')) return; const {error}=await supabase.from('posts').delete().eq('id',p.id); if(error){ toast('ลบไม่สำเร็จ'); return; } location.hash='#news'; }; } }
function card(p){ const open=`location.hash='#post?id=${p.id}'`; const d=new Date(p.published_at||new Date()).toLocaleDateString('th-TH'); const img=p.cover_url?`<img class="w-16 h-16 object-cover rounded-lg border border-[#E6EAF0]" src="${p.cover_url}" alt="cover">`:`<div class="w-16 h-16 rounded-lg bg-[#EAF2FF] grid place-items-center text-brand">📰</div>`; return `<article class="tilt p-3 border border-[#E6EAF0] rounded-xl bg-white flex items-center gap-3 cursor-pointer" onclick="${open}">${img}<div class="flex-1"><div class="font-semibold line-clamp-2">${e(p.title)}</div><div class="text-[12px] text-gray-500">${e(p.category||'ทั่วไป')} • ${d}</div></div><div class="text-brand text-sm">อ่านต่อ ›</div></article>`; }
async function isEditor(created_by){ const {data:session}=await supabase.auth.getUser(); const u=session.user; if(!u) return false; if(created_by&&created_by===u.id) return true; const {data}=await supabase.from('editors').select('user_id').eq('user_id',u.id).maybeSingle(); return !!data; }
function empty(t){ return `<div class="text-gray-500">${e(t)}</div>`; }
function e(s){ return (s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); }